name: Auto Push and Create Pull Request

on:
  push:
    branches:
      - feat/setup_cicd  # Change this to your working branch if necessary.

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name mohit.patel
          git config --global user.email mohit.patel@mindinventory.com

      - name: Commit changes and push
        run: |
          git add .
          git commit -m "Automated commit from GitHub Actions"
          git push origin Development  # Change 'main' if needed.

  create_pr:
    runs-on: ubuntu-latest
    needs: push
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: feat/setup_cicd  # Replace this with the branch you're pushing from.
          base: Development  # The branch you're merging into.
          title: "Automated PR for latest changes"
          body: "This PR is automatically generated by GitHub Actions."
